trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals migue-N552VX

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- script: |
    npm install
    npm run test
  displayName: 'npm install and run test'
