name: Run docker image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - src/**
      - Dockerfile
      - package.json
jobs:
  run_docker_with_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run docker test
        run: docker run -t -v `pwd`:/app/test migueg/cc-proyecto-21-22:latest

