name: Run docker image
on:
  workflow_run:
    workflows: ["Push Docker image to multiple registries and run test"]
    branches: [main]
    types:
      - completed
      
jobs:
  run_docker_with_test:
    on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run docker test
        run: docker run -t -v `pwd`:/app/test migueg/cc-proyecto-21-22:latest

